
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSEQL = 35;
  public static final int DIVIDE = 24;
  public static final int MINUSEQL = 36;
  public static final int EQUALS = 28;
  public static final int DIVEQL = 38;
  public static final int LPAREN = 16;
  public static final int GREATER = 31;
  public static final int INT = 2;
  public static final int LESS = 30;
  public static final int FOR = 7;
  public static final int MINUS = 22;
  public static final int RPAREN = 17;
  public static final int NOT = 25;
  public static final int SEMICOLON = 20;
  public static final int AND = 26;
  public static final int OR = 27;
  public static final int COMMA = 18;
  public static final int PLUS = 21;
  public static final int ASSIGN = 19;
  public static final int LESSEQ = 32;
  public static final int IF = 4;
  public static final int TIMESEQL = 37;
  public static final int ID = 9;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int error = 1;
  public static final int PERCENT = 39;
  public static final int LCURLY = 12;
  public static final int LSQBRACKET = 14;
  public static final int VOID = 3;
  public static final int RCURLY = 13;
  public static final int INTLITERAL = 10;
  public static final int TIMES = 23;
  public static final int ELSE = 5;
  public static final int NOTEQUALS = 29;
  public static final int WHILE = 6;
  public static final int ADDROF = 34;
  public static final int RSQBRACKET = 15;
  public static final int GREATEREQ = 33;
  public static final int STRINGLITERAL = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "VOID",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "ID",
  "INTLITERAL",
  "STRINGLITERAL",
  "LCURLY",
  "RCURLY",
  "LSQBRACKET",
  "RSQBRACKET",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "ASSIGN",
  "SEMICOLON",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "NOT",
  "AND",
  "OR",
  "EQUALS",
  "NOTEQUALS",
  "LESS",
  "GREATER",
  "LESSEQ",
  "GREATEREQ",
  "ADDROF",
  "PLUSEQL",
  "MINUSEQL",
  "TIMESEQL",
  "DIVEQL",
  "PERCENT"
  };
}

